#!/bin/bash

# root check
if [ "$EUID" -ne 0 ]; then echo "Installation requires elevated privledges (please run as root)"; exit; fi

##################
# install script #
##################
cp awmrc.pa /etc/pulse/default.pa.d/
